site_name: miniTRASGO
site_url: https://cayesoneira.github.io/miniTRASGO/
nav:
    - Home:
        - home/index.md
        - Motivation: motivation.md
        - About: about.md
        - Publications: publications.md
    - Setup:
        - setup/index.md
        - Hardware and design: hardware.md
        - Software Environment: environment.md
    - Operation:
        - operation/index.md
        - Software: software.md
        - Monitoring: control.md
        - Variables and diagram: variables.md
    - Tasks, notes and objectives:
        - tasks/index.md
        - Objectives: objectives.md
        - Tasks: todo.md
        - Notes: notes.md
    - Help:
        - help/index.md
        - Troubleshooting: troubleshooting.md
        - FAQ: frequent.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
  logo: assets/logo.png
  favicon: images/favicon.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
