site_name: miniTRASGO
#site_url: https://cayesoneira.github.io/miniTRASGO/
site_url: http://nuc1.fis.ucm.es/minitrasgo
nav:
    - Home:
        - index.md
        - Motivation: home/motivation.md
        - About: home/about.md
        - Publications: home/publications.md
    - Detector Setup:
        - setup/index.md
        - Hardware and design: setup/hardware.md
        - Software Environment: setup/environment.md
    - Operation:
        - operation/index.md
        - Software: operation/software.md
        - Monitoring: operation/monitoring.md
        - Data and Analysis: operation/analysis.md
        - Variables and diagram: operation/variables.md
    - Tasks, notes and objectives:
        - tasks/index.md
        - Tasks: tasks/todo.md
        - Notes: tasks/notes.md
        - Objectives: tasks/objectives.md
    - Help:
        - help/index.md
        - Troubleshooting: help/troubleshooting.md
        - FAQ: frequent.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
  logo: assets/logo.png
  favicon: images/favicon.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
