site_name: miniTRASGO
site_url: https://cayesoneira.github.io/miniTRASGO/
nav:
    - Home: index.md
    - The telescope:
        - Hardware and design: hardware.md
        - Software: software.md
        - Variables and diagrams: variables.md
    - Tasks and monitoring:
        - Monitoring: control.md
        - To do: todo.md
        - Objectives: objectives.md
    - Troubleshooting: troubleshooting.md
    - About: about.md
    - Notes: notes.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
