site_name: miniTRASGO
site_url: https://cayesoneira.github.io/miniTRASGO/
nav:
    - Home: index.md
    - Hardware and design: hardware.md
    - Software: software.md
    - Control: control.md
    - About: about.md
    - To do: todo.md
    - Troubleshooting: troubleshooting.md
    - Variables and diagrams: variables.md
theme:
  name: material
  palette:
    scheme: slate
